{% set name = "gtsam" %}
{% set version = "4.2.0" %}

package:
  name: gtsam
  version: '{{ version }}'

source:
  git_url: https://github.com/borglab/gtsam.git
  git_rev: "HEAD"
  git_depth: 1
  patches:
    - unvendor-pybind11.patch
    - fix-python-build-win.patch  # [win]
    - fix-boost.patch  # [win]
    - fix-missing-includes.patch

build:
  number: 4
  run_exports:
    - '{{ pin_subpackage(name, max_pin="x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - {{ stdlib("c") }}
    - '{{ compiler("cxx") }}'
    - ninja
    - cmake
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - libboost-devel
    - eigen
    - geographiclib-cpp
    - metis
    - suitesparse
    - tbb
    - tbb-devel
    - pybind11
    - pyparsing
    - numpy
    - setuptools
    - pip
  run:
    - python
    - pyparsing
    - numpy

test:
  commands:
    - test -f ${PREFIX}/lib/libgtsam${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/cmake/gtwrap/gtwrapConfig.cmake  # [not win]
    - test -f ${PREFIX}/lib/cmake/GTSAM/GTSAMConfig.cmake  # [not win]
    - test -f ${PREFIX}/include/gtsam/base/types.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\gtsam\\base\\types.h (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\gtsam.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\gtsam.dll (exit 0) else (exit 1)  # [win]
  imports:
    - gtsam


about:
  home: https://github.com/borglab/gtsam
  summary: GTSAM is a library of C++ classes that implement smoothing and mapping (SAM) in robotics and vision
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE.BSD

extra:
  recipe-maintainers:
    - wolfv
    - ameysutavani
    - Tobias-Fischer
    - traversaro
